Your Ontology Class Name,BFO Top-Level,BFO Mid-Level / Specific Type,CCO Alignment / Equivalent Class,IOF Alignment / Equivalent Class,Brief Description,Example Individuals / Values from DSQ
myOnt:CircuitCardAssembly,BFO:Continuant,BFO:Material Entity (specifically BFO:Object),cco:ManufacturedProduct / cco:Artifact,iof-core:MaterialArtifact / iof-core:Product,A physical circuit card assembly.,cca_XYZ123
myOnt:ElectronicComponent,BFO:Continuant,BFO:Material Entity (specifically BFO:Object),cco:Component / cco:Artifact,iof-core:Part / iof-core:MaterialArtifact,A physical electronic component on a CCA.,The U1 component on cca_XYZ123
myOnt:ComponentPin,BFO:Continuant,BFO:Material Entity,cco:Part / cco:FeatureOfInterest,iof-core:Part / iof-core:FeatureOfInterest,A physical pin or pad of an electronic component.,pin3 of component U1
myOnt:SolderPasteDeposit,BFO:Continuant,BFO:Material Entity (specifically BFO:ObjectAggregate or BFO:PortionOfMatter),cco:PortionOfMatter / cco:MaterialEntity,iof-core:BulkMaterialEntity / iof-core:MaterialEntity,A specific physical deposit of solder paste on a CCA pad, prior to reflow.,The solder paste deposit at U1-pin3 on cca_XYZ123
myOnt:SolderJoint,BFO:Continuant,BFO:Material Entity (specifically BFO:Object),cco:Object / cco:FeatureOfInterest,iof-core:MaterialArtifact / iof-core:FeatureOfInterest,"A physical solder joint formed after reflow, connecting a component pin to a CCA pad.",The solder joint at U1-pin3 on cca_XYZ123
myOnt:PhysicalVolume,BFO:Continuant,BFO:Specifically Dependent Continuant (BFO:Quality),cco:Volume (Quality),iof-core:Quality (would reference QUDT for specific quantity kind),The actual 3D extent of a material entity.,The inherent volume of the SolderPasteDeposit at U1-pin3
myOnt:PhysicalHeight,BFO:Continuant,BFO:Specifically Dependent Continuant (BFO:Quality),cco:Height (Quality),iof-core:Quality (would reference QUDT for specific quantity kind),The actual height of a material entity relative to a reference plane.,The inherent height of the SolderPasteDeposit at U1-pin3
myOnt:PositionalOffset,BFO:Continuant,BFO:Specifically Dependent Continuant (BFO:Quality),cco:Position / cco:Quality (representing offset),iof-core:Quality (would reference QUDT for specific quantity kind),The actual displacement of a material entity from a target position.,The inherent offset of the SolderPasteDeposit at U1-pin3
myOnt:VoidingLevel,BFO:Continuant,BFO:Specifically Dependent Continuant (BFO:Quality),cco:Quality (e.g. cco:VoidFraction),iof-core:Quality (would reference QUDT for specific quantity kind),"The actual extent of voids within a solder joint, often expressed as a percentage.",The inherent voiding level of the SolderJoint at U1-pin3
myOnt:SerialNumber,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Identifier / cco:InformationBearingEntity,iof-core:InformationContentEntity / iof-core:Identifier,"An identifier string that uniquely designates a CCA.","XYZ123"
myOnt:ReferenceDesignator,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Identifier / cco:InformationBearingEntity,iof-core:InformationContentEntity / iof-core:Identifier,"An identifier for a component's location/instance on a CCA.","U1"
myOnt:PinIdentifier,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Identifier / cco:InformationBearingEntity,iof-core:InformationContentEntity / iof-core:Identifier,"An identifier for a pin on a component.","3" (for pin3)
myOnt:SPIMeasurementDatum,BFO:Continuant,BFO:Generically Dependent Continuant,cco:MeasurementDatum / cco:InformationBearingEntity,iof-core:InformationContentEntity (that is_about a quality),"A piece of information representing a measurement taken during SPI. It's *about* a quality of a SolderPasteDeposit.",An instance representing the volume measurement for U1-pin3
myOnt:XRayFindingDatum,BFO:Continuant,BFO:Generically Dependent Continuant,cco:ObservationDatum / cco:InformationBearingEntity,iof-core:InformationContentEntity (that is_about a material entity or quality),"A piece of information representing a finding from an X-ray inspection. It's *about* a SolderJoint.",An instance representing the 'Voiding > 25%' finding for U1-pin3
myOnt:NonConformanceType,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Type / cco:InformationBearingEntity,iof-core:InformationContentEntity (representing a classification),A classification of a non-conformance.,ncType:VoidingOver25Percent
myOnt:MeasurementType,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Type / cco:InformationBearingEntity,iof-core:InformationContentEntity (representing a classification of measurement),A classification of what is being measured.,"measurementType:Volume, measurementType:Height, measurementType:Offset"
myOnt:MeasurementValue,BFO:Continuant,BFO:Generically Dependent Continuant,cco:Datum / cco:InformationBearingEntity,iof-core:InformationContentEntity (specifically a value, often linked to QUDT),The numerical value part of a measurement datum.,"e.g., 750000.0 (for volume), 150.0 (for height)"
myOnt:MeasurementUnit,BFO:Continuant,BFO:Generically Dependent Continuant,cco:UnitOfMeasure / cco:InformationBearingEntity,iof-core:InformationContentEntity (specifically a unit, often linked to QUDT),The unit of measure for a measurement value.,"unit:CubicMicrometer, unit:Micrometer"
myOnt:ScreenPrintingProcess,BFO:Occurrent,BFO:Process,cco:ManufacturingProcess / cco:Process,iof-core:ManufacturingProcess / iof-core:Process,The manufacturing process that creates solder paste deposits.,The specific screen printing event for cca_XYZ123
myOnt:SPIProcess,BFO:Occurrent,BFO:Process,cco:InspectionProcess / cco:Process,iof-core:InspectionProcess / iof-core:Process,The inspection process that measures solder paste deposits.,The specific SPI event for cca_XYZ123
myOnt:ReflowProcess,BFO:Occurrent,BFO:Process,cco:ManufacturingProcess / cco:Process,iof-core:ManufacturingProcess / iof-core:Process,"The manufacturing process that transforms solder paste deposits into solder joints.",The specific reflow event for cca_XYZ123
myOnt:XRayInspectionProcess,BFO:Occurrent,BFO:Process,cco:InspectionProcess / cco:Process,iof-core:InspectionProcess / iof-core:Process,"The inspection process that examines solder joints using X-ray.",The specific X-ray inspection event for cca_XYZ123
